from enum import Enum

class DocumentType(str, Enum):
    ADMISSION_NOTE = "ADMISSION_NOTE"
    DISCHARGE_SUMMARY = "DISCHARGE_SUMMARY"
    LAB_REPORT = "LAB_REPORT"
    RADIOLOGY_REPORT = "RADIOLOGY_REPORT"
    BILL = "BILL"
    PRESCRIPTION = "PRESCRIPTION"
    PROGRESS_NOTE = "PROGRESS_NOTE"
    OTHER = "OTHER"
    UNKNOWN = "UNKNOWN"

class InvestigationStatus(str, Enum):
    ADVISED = "ADVISED"
    PERFORMED = "PERFORMED"
    CANCELLED = "CANCELLED"
    UNKNOWN = "UNKNOWN"

class SeverityLevel(str, Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    ESCALATION = "ESCALATION"

class FindingCategory(str, Enum):
    MISSING_DOCUMENT = "MISSING_DOCUMENT"
    INVESTIGATION_GAP = "INVESTIGATION_GAP"
    CHRONOLOGY_MISMATCH = "CHRONOLOGY_MISMATCH"
    DATE_AMBIGUITY = "DATE_AMBIGUITY"
    DIAGNOSTIC_CONTRADICTION = "DIAGNOSTIC_CONTRADICTION"
    UNCERTAIN_EXTRACTION = "UNCERTAIN_EXTRACTION"

class FindingStatus(str, Enum):
    OPEN = "OPEN"
    RESOLVED = "RESOLVED"
    OVERRIDDEN = "OVERRIDDEN"
    ESCALATED = "ESCALATED"

class ActionType(str, Enum):
    RETRIEVAL_TICKET = "RETRIEVAL_TICKET"
    CLARIFICATION_MEMO = "CLARIFICATION_MEMO"

class ReadinessStatus(str, Enum):
    INCOMPLETE = "INCOMPLETE"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    READY_FOR_HUMAN_REVIEW = "READY_FOR_HUMAN_REVIEW"
